@startuml grouping-example
!include <azure/AzureCommon>

' no azure icon for users...
!include <awslib/AWSCommon>
!include <awslib/General/Users>

!include <azure/Web/AzureAPIManagement>
!include <azure/Identity/AzureActiveDirectory>
!include <azure/Compute/AzureFunction>
!include <azure/Databases/AzureCosmosDb>

left to right direction

skinparam rectangle<<users>> {
    borderColor AZURE_BORDER_COLOR
}

skinparam rectangle<<external>> {
    backgroundColor lightgrey
    borderStyle dashed
    roundCorner 20
}
hide <<external>> stereotype

AWSEntity(sources, "Events", "millions of users", AZURE_SYMBOL_COLOR, Users, Users)

rectangle "App" {
    rectangle "External Subnet" as r <<external>> {
        AzureAPIManagement(votingAPI, "Voting API", "user votes")
        AzureFunction(recordVote, "Record Vote", "enter or update vote per user")
    }
    AzureCosmosDb(voteDb, "Vote Database", "one entry per user")
}

package "Security" {
    AzureActiveDirectory(userAuth, "User Authentication", "JWT to submit votes")
    AzureFunction(generateToken, "User Credentials", "return JWT")
}

sources --> userAuth
sources --> votingAPI
userAuth <--> generateToken
votingAPI --> recordVote
recordVote --> voteDb

@enduml