@startuml deployment-tags-and-sprites
!include <C4/C4_Deployment>
!include <tupadr3/common>
!include <tupadr3/devicons2/angularjs>
!include <tupadr3/devicons2/java>
!include <tupadr3/devicons2/oracle_original>
!include <tupadr3/devicons2/tomcat_line>
!include <tupadr3/font-awesome/mobile>

!global $LIGHT_BLUE = "#a5cbf0"
!global $LIGHT_GREY = "#cccccc"

AddElementTag("standby", $bgColor=$LIGHT_BLUE, $borderColor=$LIGHT_BLUE)
AddElementTag("standbyNode", $fontColor=$LIGHT_GREY, $borderColor=$LIGHT_GREY)
AddRelTag("standby", $textColor=$LIGHT_GREY, $lineColor=$LIGHT_GREY)

Deployment_Node(computer, "Customer's computer", "Microsoft Windows or Apple macOS") {
    Deployment_Node(webBrowser, "Web Browser", "Chrome, Firefox, Safari or Edge") {
        Container(spa, "Single-Page Application", "JavaScript and Angular", "Provides all of the internet banking functionality to customers via their web browser.", $sprite="angularjs")
    }
}

Deployment_Node(mobileDevice, "Customer's mobile device", "Apple iOS or Android") {
    Container(mobileApp, "Mobile App", "Xamarin", "Provides a limited subset of the internet banking functionality to customers via their mobile device.", $sprite="mobile")
}

Deployment_Node(dc, "Big Bank Plc", "Big Bank Plc's data centre") {
    Deployment_Node(apiServers, "bigbank-api<nn>", "Ubuntu 16.04 LTS", "x8") {
        Deployment_Node(tomcatApi, "Apache Tomcat", "Apache Tomcat 8.x") {
            Container(api, "API Application", "Java and Spring MVC", "Provides internet banking functionality via a JSON/HTTPS API.", $sprite="tomcat_line")
        }
    }

    Deployment_Node(webServers, "bigbank-web<nn>", "Ubuntu 16.04 LTS", "x4") {
        Deployment_Node(tomcatWeb, "Apache Tomcat", "Apache Tomcat 8.x") {
            Container(web, "Web Application", "Java and Spring MVC", "Delivers the static content and the Internet banking single page application.", $sprite="tomcat_line")
        }
    }

    Deployment_Node(dbServer1, "bigbank-db01", "Ubuntu 16.04 LTS") {
        Deployment_Node(dbInstance1, "Oracle - Primary", "Oracle 12c") {
            ContainerDb(db1, "Database", "Oracle Database Schema", "Stores user registration information, hashed authentication credentials, access logs etc.", $sprite="oracle_original")
        }
    }

    Deployment_Node(dbServer2, "bigbank-db02", "Ubuntu 16.04 LTS", $tags="standbyNode") {
        Deployment_Node(dbInstance2, "Oracle - Secondary", "Oracle 12c", $tags="standbyNode") {
            ContainerDb(db2, "Database", "Oracle Database Schema", "Stores user registration information, hashed authentication credentials, access logs etc.", $tags="standby", $sprite="oracle_original")
        }
    }
}

Rel(mobileApp, api, "Makes API calls to", "JSON/HTTPS")
Rel(spa, api, "Makes API calls to", "JSON/HTTPS")

Rel(web, spa, "Delivers to the customer's web browser")

Rel(api, db1, "Reads from and writes to", "JDBC")
Rel(api, db2, "Reads from and writes to", "JDBC", $tags="standby")
Rel_L(db1, db2, "Replicates data to", $tags="standby")

caption Deployment Diagram for Internet Banking System

@enduml